### ISSUE TITLE
pulseaudio-qt issue

### ISSUE THREAD

**Issue by g6avk** [solopasha/kde6-copr#2]
Hi,

I hope it is OK to report this here?

I ran into an issue this morning while updating my system:

  - cannot install both pulseaudio-qt-1.3^20231120.081305.36f5625-1.fc39.x86_64 and pulseaudio-qt-1.4.0-2.fc39.x86_64
  - cannot install both pulseaudio-qt-1.3^20240108.f8ef220-1.fc39.x86_64 and pulseaudio-qt-1.4.0-2.fc39.x86_64
  - cannot install the best update candidate for package pulseaudio-qt-1.4.0-1.fc39.x86_64
  - cannot install the best update candidate for package kde-connect-libs-24.01.90-1.fc39.x86_64

**Comment by solopasha** [comment]
Should be fixed https://copr.fedorainfracloud.org/coprs/solopasha/kde6/build/6924601. (I don't have updates-testing enabled, so I may be late to spot these conflicts)

**Comment by g6avk** [comment]
All is OK now, thank you.
