### ISSUE TITLE
Create Fedora 40 repo

### ISSUE THREAD

**Issue by Everest10** [solopasha/kde6-copr#3]
I want to request to recreate the kde 6 repo to fedora 40.

I thank you, !

Best regards.

**Comment by solopasha** [comment]
I wasn't planning on doing that. Is there a reason to do so? KDE megarelease 6 is packaged in Fedora 40 and the KDE SIG updates those packages fairly quick.

**Comment by g6avk** [comment]
I had the same question, my reason was that Fedora always seemed to be way behind with the Apps/PIM packages, for example FC39 is on Apps 23.08.4
I don't know but maybe this has changed now?
Thanks very much for your repo's which I will continue to use.

**Comment by solopasha** [comment]
enabled f40.
