### ISSUE TITLE
kdepim-addons

### ISSUE THREAD

**Issue by g6avk** [solopasha/kde6-copr#5]
Thanks for the Fedora 40 builds,
I updated today and all went well. However on checking if all packages where updated I found that kdepim-addons is still @ version 24.05.1-1. Missed build maybe?

**Comment by solopasha** [comment]
It failed to build https://copr.fedorainfracloud.org/coprs/solopasha/kde6/build/7708762/. I will investigate later (I'm away from my desk for a couple of days). But this should be fine, there are no code changes in .2.

**Comment by solopasha** [comment]
https://copr.fedorainfracloud.org/coprs/solopasha/kde6/build/7716826/
