### ISSUE TITLE
since 6.2.1, login to plasma takes a very long time

### ISSUE THREAD

**Issue by slartibart70** [solopasha/kde6-copr#7]
Any idea what this may cause?
System is up to date / did a distrosync... 
(in comparison, 6.2.0 was nearly instant after giving the password and until the desktop was rendered/active)

**Comment by slartibart70** [comment]
and thanks for providing these updates in a timely manner!!!

**Comment by solopasha** [comment]
Yep, I also noticed this. Downgrading plasma-workspace fixes the issue. Will try to find out what causes this

**Comment by slartibart70** [comment]
does it help to provide journalctl-logs?

**Comment by slartibart70** [comment]
yes, downgrade of plasma-workspace helps. Same speed as before.

**Comment by g6avk** [comment]
Confirm fixed, thanks very much for the fast fix 👍🏻
